version: '3.5'
services:
    client:
        build: .
    api:
        image: nginx:1-alpine
        ports:
            - 8080:80
        environment:
            - NGINX_PORT=80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        restart: unless-stopped
    warsa:
        image: warsa-fuseki
    pnr:
        image: pnr-fuseki
    history:
        image: history-fuseki
